#!/bin/bash

###########################################################################
#          Title: Kamino: Zeroize Drive - Multi
#         Author: Mike Del Pozzo
#    Description: This script will wipe multiple drives simultaneously by
#                 filling them with zeroes.
#        Version: 1.0.0
#           Date: 16 January 2019
#        Website: https://github.com/delpozzo/kamino
#        License: GPLv3 (see LICENSE)
#
#    Kamino Copyright (C) 2019 Mike Del Pozzo
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    any later version.
###########################################################################

declare -a targetDriveArray
scriptDir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null && pwd)"
kaminoConfig="$scriptDir/../kamino.config"
blockSize=$(grep 'block_size' $kaminoConfig | cut -d ' ' -f2)
tmpDir=$(grep 'tmp_directory' $kaminoConfig | cut -d ' ' -f2)
tmpPID="$tmpDir/zeroizeDrive-$(cat /dev/urandom  |tr -dc 'a-zA-Z0-9' |fold -w 8 |head -n1).pid"
protectRootFilesystem=$(grep 'protect_root_filesystem' $kaminoConfig | cut -d ' ' -f2)
if [ "$protectRootFilesystem" = 'no' ]; then 
  rootPartition=/dev/null
else
  rootPartition=$(mount |grep 'on / type' |grep -o 'sd[a-z]')
fi

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;36m'
NOCOLOR='\033[0m'

###########################################################################

displaySplash() {
  echo ''
  echo ' K A M I N O    [ver. 1.0.0]'
  echo ' ---------------------------------------'
  echo ' Z E R O I Z E   D R I V E  -  M U L T I'
  echo ''
}

###########################################################################

getDriveInfo() {
  local driveSectors=$(cat /sys/block/$1/size | awk '{$1=$1};1')
  local sectorSize=$(cat /sys/block/$1/queue/hw_sector_size | awk '{$1=$1};1')
  local driveVendor=$(cat /sys/block/$1/device/vendor | awk '{$1=$1};1')
  local driveModel=$(cat /sys/block/$1/device/model | awk '{$1=$1};1')
  local driveSize=$(awk -v var1="$driveSectors" -v var2="$sectorSize" 'BEGIN {print var1*var2/1000000000}')

  echo  "/dev/$1  $driveSize GB  $driveVendor $driveModel"
}

###########################################################################

containsElement() {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

###########################################################################

zeroizeDrive() {
  local ddCommand="dd if=/dev/zero bs=$blockSize | tee"
  local userInput

  for ((i=0; i<${#targetDriveArray[@]}; i++))
  do
    if [ $(($i+1)) = ${#targetDriveArray[@]} ]; then
      ddCommand="${ddCommand} | dd of=/dev/${targetDriveArray[i]} bs=$blockSize"
    else
      ddCommand="${ddCommand} >(dd of=/dev/${targetDriveArray[i]} bs=$blockSize)"
    fi
  done

  while true; do
    clear
    displaySplash

    echo -e "You've selected to zeroize ${BLUE}multiple drives${NOCOLOR} with the following command:"
    echo ''
    echo  "  $ddCommand"
    echo ''
    echo -e "${RED}!!!WARNING!!!${NOCOLOR} All data on the target drives will be wiped and lost forever."
    echo ''
    echo 'Do you wish to proceed?'
    echo ''
    echo -e ' [ Y ]\tYes'
    echo -e ' [ N ]\tNo'
    echo -e ' [ Q ]\tExit to Main Menu'

    echo ''
    echo 'Enter selection: '

    read userInput

    if [ "$userInput" = 'q' ] || [ "$userInput" = 'Q' ]; then
      clear
      echo ''
      echo 'Exiting Zeroize Drive...'
      echo ''
      exit 1

    elif [ "$userInput" = 'n' ] || [ "$userInput" = 'N' ]; then
      unset targetDriveArray
      declare -a targetDriveArray
      clear
      return

    elif [ "$userInput" = 'y' ] || [ "$userInput" = 'Y' ]; then

      bash -c "$ddCommand & ps -C dd -o pid= > $tmpPID"

      while true; do
        clear
        displaySplash

        echo "  $ddCommand"
        echo ''
        echo -e "${GREEN}!!!INFO!!!${NOCOLOR} Data wipe is now in progress. This may take a while..."
        echo ''

        kill -s USR1 $(cat $tmpPID) > /dev/null 2>&1

        if [ $? -ne 0 ]; then
          rm -f $tmpPID > /dev/null 2>&1
          break
        fi

        sleep 3
      done

      sync

      echo ''
      echo -e "${GREEN}!!!INFO!!!${NOCOLOR} Data wipe complete. Press enter to return to main menu..."
      echo ''

      read userInput

      exit 0

    else
      echo ''
      echo 'Invalid selection, try again...'
      sleep 2
      continue
    fi
  done
}

###########################################################################

listDrives() {
  local userInput
  local userInputArray

  while true; do
    clear
    displaySplash

    IFS=$'\n'
    local driveArray=($(cat /proc/partitions |grep -o 'sd[a-z]' |grep -v "$rootPartition" |sort -u))
    unset IFS

    if [ ${#driveArray[@]} -gt 1 ]; then
      echo -e "Choose ${BLUE}two or more${NOCOLOR} drives to wipe from the list below (comma-separated):"
      echo ''

      for ((i=0; i<${#driveArray[@]}; i++))
      do
        local driveInfo=$(getDriveInfo ${driveArray[i]})
        echo -e " [ $(($i+1)) ]\t$driveInfo"
      done

      echo ''
      echo 'Or select from the following options:'
      echo ''
      echo -e ' [ R ]\tRefresh Drive List'
      echo -e ' [ Q ]\tExit to Main Menu'

      echo ''
      echo 'Enter selection: '

      read userInput

      if [ "$userInput" = 'q' ] || [ "$userInput" = 'Q' ]; then
        clear
        echo ''
        echo 'Exiting Zeroize Drive...'
        echo ''
        exit 1

      elif [ "$userInput" = 'r' ] || [ "$userInput" = 'R' ]; then
        clear
        continue

      elif [[ "$userInput" =~ ^[0-9]{1}\,[0-9]{1}$ ]] || [[ "$userInput" =~ ^[0-9]{1}\,[0-9]{1}\,[0-9]{1}$ ]] || [[ "$userInput" =~ ^[0-9]{1}\,[0-9]{1}\,[0-9]{1}\,[0-9]{1}$ ]]; then
        IFS=','
        read -r -a userInputArray <<< "$userInput"
        unset IFS

        for item in "${userInputArray[@]}"
        do
          if [ "$item" -gt 0 -a "$item" -le ${#driveArray[@]} ]; then
              containsElement "${driveArray[$((item-1))]}" "${targetDriveArray[@]}"
              if [ $? -eq 1 ]; then
                targetDriveArray+=("${driveArray[$((item-1))]}")
                echo "Adding ${driveArray[$((item-1))]}"
              else
                echo 'Invalid selection, try again...'
                unset targetDriveArray
                declare -a targetDriveArray
                sleep 2
                break
              fi
          else
            echo 'Invalid selection, try again...'
            unset targetDriveArray
            declare -a targetDriveArray
            sleep 2
            break
          fi
        done

        if [ ${#targetDriveArray[@]} -gt 1 ]; then
          zeroizeDrive
          continue
        fi

      else
        echo ''
        echo 'Invalid selection, try again...'
        unset targetDriveArray
        declare -a targetDriveArray
        sleep 2
        continue
      fi

    else
      echo -e "Please attach ${BLUE}two or more${NOCOLOR} target drives to the system and try again."
      echo ''
      echo -e ' [ R ]\tRefresh Drive List'
      echo -e ' [ Q ]\tExit to Main Menu'

      echo ''
      echo 'Enter selection: '

      read userInput

      if [ "$userInput" = 'q' ] || [ "$userInput" = 'Q' ]; then
        clear
        echo ''
        echo 'Exiting Zeroize Drive...'
        echo ''
        exit 1

      elif [ "$userInput" = 'r' ] || [ "$userInput" = 'R' ]; then
        clear
        continue

      else
        echo ''
        echo 'Invalid selection, try again...'
        sleep 2
        continue
      fi
    fi
  done
}

###########################################################################

if [ "$(id -u)" != 0 ]; then
  echo 'This script must be run with sudo or as root!'
  exit 1
fi

clear
listDrives
